config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                                          Controller#Action
#     plane_flight_reservations GET    /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#index
#                               POST   /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#create
#  new_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#show
#                               PATCH  /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               PUT    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               DELETE /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 plane_flights GET    /planes/:plane_id/flights(.:format)                                  flights#index
#                               POST   /planes/:plane_id/flights(.:format)                                  flights#create
#              new_plane_flight GET    /planes/:plane_id/flights/new(.:format)                              flights#new
#             edit_plane_flight GET    /planes/:plane_id/flights/:id/edit(.:format)                         flights#edit
#                  plane_flight GET    /planes/:plane_id/flights/:id(.:format)                              flights#show
#                               PATCH  /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               PUT    /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               DELETE /planes/:plane_id/flights/:id(.:format)                              flights#destroy
#                        planes GET    /planes(.:format)                                                    planes#index
#                               POST   /planes(.:format)                                                    planes#create
#                     new_plane GET    /planes/new(.:format)                                                planes#new
#                    edit_plane GET    /planes/:id/edit(.:format)                                           planes#edit
#                         plane GET    /planes/:id(.:format)                                                planes#show
#                               PATCH  /planes/:id(.:format)                                                planes#update
#                               PUT    /planes/:id(.:format)                                                planes#update
#                               DELETE /planes/:id(.:format)                                                planes#destroy
#                       flights GET    /flights(.:format)                                                   flights#index
#                               POST   /flights(.:format)                                                   flights#create
#                    new_flight GET    /flights/new(.:format)                                               flights#new
#                   edit_flight GET    /flights/:id/edit(.:format)                                          flights#edit
#                        flight GET    /flights/:id(.:format)                                               flights#show
#                               PATCH  /flights/:id(.:format)                                               flights#update
#                               PUT    /flights/:id(.:format)                                               flights#update
#                               DELETE /flights/:id(.:format)                                               flights#destroy
#                         users GET    /users(.:format)                                                     users#index
#                               POST   /users(.:format)                                                     users#create
#                      new_user GET    /users/new(.:format)                                                 users#new
#                     edit_user GET    /users/:id/edit(.:format)                                            users#edit
#                          user GET    /users/:id(.:format)                                                 users#show
#                               PATCH  /users/:id(.:format)                                                 users#update
#                               PUT    /users/:id(.:format)                                                 users#update
#                               DELETE /users/:id(.:format)                                                 users#destroy
#                          root GET    /                                                                    pages#app
#                        signup GET    /signup(.:format)                                                    pages#signup
#                         login GET    /login(.:format)                                                     pages#login
#                               POST   /login(.:format)                                                     session#create
#                               DELETE /login(.:format)                                                     session#destroy
#

Rails.application.routes.draw do

  resources :planes do
    resources :flights do
      resources :reservations
    end
  end

  resources :reservations
  resources :flights
  resources :users
  root :to => 'pages#app'

  get '/signup' => 'pages#signup'
  get '/login' => 'pages#login'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/plane.rb
# == Schema Information
#
# Table name: planes
#
#  id         :integer          not null, primary key
#  rows       :integer
#  columns    :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Plane < ActiveRecord::Base
  has_many :flights
  has_many :reservations, through: :flights
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  before_action :set_plane, only: [:show, :edit, :update, :destroy]

  # GET /planes
  # GET /planes.json
  def index
    @planes = Plane.all
  end

  # GET /planes/1
  # GET /planes/1.json
  def show
    @flights = Flight.where :plane_id => @plane.id
  end

  # GET /planes/new
  def new
    @plane = Plane.new
  end

  # GET /planes/1/edit
  def edit
  end

  # POST /planes
  # POST /planes.json
  def create
    @plane = Plane.new(plane_params)

    respond_to do |format|
      if @plane.save
        format.html { redirect_to @plane, notice: 'Plane was successfully created.' }
        format.json { render :show, status: :created, location: @plane }
      else
        format.html { render :new }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planes/1
  # PATCH/PUT /planes/1.json
  def update
    respond_to do |format|
      if @plane.update(plane_params)
        format.html { redirect_to @plane, notice: 'Plane was successfully updated.' }
        format.json { render :show, status: :ok, location: @plane }
      else
        format.html { render :edit }
        format.json { render json: @plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planes/1
  # DELETE /planes/1.json
  def destroy
    @plane.destroy
    respond_to do |format|
      format.html { redirect_to planes_url, notice: 'Plane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plane
      @plane = Plane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plane_params
      params.require(:plane).permit(:rows, :columns, :name)
    end
end

app/helpers/planes_helper.rb
module PlanesHelper
end

app/views/planes/_form.html.erb
<%= form_for(@plane) do |f| %>
  <% if @plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plane.errors.count, "error") %> prohibited this plane from being saved:</h2>

      <ul>
      <% @plane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rows %><br>
    <%= f.number_field :rows %>
  </div>
  <div class="field">
    <%= f.label :columns %><br>
    <%= f.number_field :columns %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/planes/edit.html.erb
<h1>Editing Plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @plane %> |
<%= link_to 'Back', planes_path %>

app/views/planes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Planes</h1>

<table>
  <thead>
    <tr>
      <th>Rows</th>
      <th>Columns</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planes.each do |plane| %>
      <tr>
        <td><%= plane.rows %></td>
        <td><%= plane.columns %></td>
        <td><%= plane.name %></td>
        <td><%= link_to 'Show', plane %></td>
        <td><%= link_to 'Edit', edit_plane_path(plane) %></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plane', new_plane_path %>

app/views/planes/new.html.erb
<h1>New Plane</h1>

<%= render 'form' %>

<%= link_to 'Back', planes_path %>

app/views/planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rows:</strong>
  <%= @plane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @plane.columns %>
</p>

<p>
  <strong>Name:</strong>
  <%= @plane.name %>
</p>

<p>
  <strong>Flights:</strong>
  <% i = 1 %>
  <% @flights.each do |flight| %>
    <div><%= "Flight #{i}: " %><% i += 1 %>
      <td><%= flight.origin %></td>
      <td><%= "to #{flight.destination}" %></td>
      <td><%= flight.date %></td>
      <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_plane_path(@plane) %> |
<%= link_to 'New Flight', new_flight_path %> |
<%= link_to 'Back', planes_path %>