config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                                          Controller#Action
#     plane_flight_reservations GET    /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#index
#                               POST   /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#create
#  new_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#show
#                               PATCH  /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               PUT    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               DELETE /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 plane_flights GET    /planes/:plane_id/flights(.:format)                                  flights#index
#                               POST   /planes/:plane_id/flights(.:format)                                  flights#create
#              new_plane_flight GET    /planes/:plane_id/flights/new(.:format)                              flights#new
#             edit_plane_flight GET    /planes/:plane_id/flights/:id/edit(.:format)                         flights#edit
#                  plane_flight GET    /planes/:plane_id/flights/:id(.:format)                              flights#show
#                               PATCH  /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               PUT    /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               DELETE /planes/:plane_id/flights/:id(.:format)                              flights#destroy
#                        planes GET    /planes(.:format)                                                    planes#index
#                               POST   /planes(.:format)                                                    planes#create
#                     new_plane GET    /planes/new(.:format)                                                planes#new
#                    edit_plane GET    /planes/:id/edit(.:format)                                           planes#edit
#                         plane GET    /planes/:id(.:format)                                                planes#show
#                               PATCH  /planes/:id(.:format)                                                planes#update
#                               PUT    /planes/:id(.:format)                                                planes#update
#                               DELETE /planes/:id(.:format)                                                planes#destroy
#                       flights GET    /flights(.:format)                                                   flights#index
#                               POST   /flights(.:format)                                                   flights#create
#                    new_flight GET    /flights/new(.:format)                                               flights#new
#                   edit_flight GET    /flights/:id/edit(.:format)                                          flights#edit
#                        flight GET    /flights/:id(.:format)                                               flights#show
#                               PATCH  /flights/:id(.:format)                                               flights#update
#                               PUT    /flights/:id(.:format)                                               flights#update
#                               DELETE /flights/:id(.:format)                                               flights#destroy
#                         users GET    /users(.:format)                                                     users#index
#                               POST   /users(.:format)                                                     users#create
#                      new_user GET    /users/new(.:format)                                                 users#new
#                     edit_user GET    /users/:id/edit(.:format)                                            users#edit
#                          user GET    /users/:id(.:format)                                                 users#show
#                               PATCH  /users/:id(.:format)                                                 users#update
#                               PUT    /users/:id(.:format)                                                 users#update
#                               DELETE /users/:id(.:format)                                                 users#destroy
#                          root GET    /                                                                    pages#app
#                        signup GET    /signup(.:format)                                                    pages#signup
#                         login GET    /login(.:format)                                                     pages#login
#                               POST   /login(.:format)                                                     session#create
#                               DELETE /login(.:format)                                                     session#destroy
#

Rails.application.routes.draw do

  resources :planes do
    resources :flights do
      resources :reservations
    end
  end

  resources :reservations
  resources :flights
  resources :users
  root :to => 'pages#app'

  get '/signup' => 'pages#signup'
  get '/login' => 'pages#login'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/flight.rb
# == Schema Information
#
# Table name: flights
#
#  id          :integer          not null, primary key
#  origin      :string
#  destination :string
#  date        :datetime
#  plane_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Flight < ActiveRecord::Base
  has_many :reservations
  belongs_to :plane
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    if params[:plane_id]
      @flights = Flight.where :plane_id => params[:plane_id]
    else 
      @flights = Flight.all
    end
    render :json => @flights
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @reservations = Reservation.where :flight_id => @flight.id
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end

    rows = @flight.plane.rows
    columns = @flight.plane.columns

    for row in 1..rows
      for column in 1..columns
        @reservation = Reservation.new
        @reservation.row = row
        @reservation.column = column
        @reservation.user_id = nil
        @reservation.save
        @flight.reservations << @reservation
      end
    end

  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:origin, :destination, :date, :plane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :plane_id %><br>
    <%= f.collection_select :plane_id, Plane.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Origin</th>
      <th>Destination</th>
      <th>Date</th>
      <th>Plane</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @flights.length == nil %>
      <tr>
        <td> There are no flights. </td>
      </tr>
    <% else %>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.origin %></td>
          <td><%= flight.destination %></td>
          <td><%= flight.date %></td>
          <td><%= flight.plane_id %></td>
          <td><%= link_to 'Show', flight %></td>
          <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
          <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @flight.origin %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane_id %>
</p>

<p>
  <strong>Reservations:</strong>
  <% i = 1 %>
  <% @reservations.each do |rsvp| %>
    <div><%= "Reservation #{i}: " %><% i += 1 %>
      <td><%= "Row: #{rsvp.row}" %></td>
      <td><%= "Col: #{rsvp.column}" %></td>
      <td><%= link_to 'Edit', edit_reservation_path(rsvp) %></td>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'New Reservation', new_reservation_path %> |
<%= link_to 'Back', flights_path %>