config/routes.rb
# == Route Map
#
#                        Prefix Verb   URI Pattern                                                          Controller#Action
#     plane_flight_reservations GET    /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#index
#                               POST   /planes/:plane_id/flights/:flight_id/reservations(.:format)          reservations#create
#  new_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/new(.:format)      reservations#new
# edit_plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id/edit(.:format) reservations#edit
#      plane_flight_reservation GET    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#show
#                               PATCH  /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               PUT    /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#update
#                               DELETE /planes/:plane_id/flights/:flight_id/reservations/:id(.:format)      reservations#destroy
#                 plane_flights GET    /planes/:plane_id/flights(.:format)                                  flights#index
#                               POST   /planes/:plane_id/flights(.:format)                                  flights#create
#              new_plane_flight GET    /planes/:plane_id/flights/new(.:format)                              flights#new
#             edit_plane_flight GET    /planes/:plane_id/flights/:id/edit(.:format)                         flights#edit
#                  plane_flight GET    /planes/:plane_id/flights/:id(.:format)                              flights#show
#                               PATCH  /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               PUT    /planes/:plane_id/flights/:id(.:format)                              flights#update
#                               DELETE /planes/:plane_id/flights/:id(.:format)                              flights#destroy
#                        planes GET    /planes(.:format)                                                    planes#index
#                               POST   /planes(.:format)                                                    planes#create
#                     new_plane GET    /planes/new(.:format)                                                planes#new
#                    edit_plane GET    /planes/:id/edit(.:format)                                           planes#edit
#                         plane GET    /planes/:id(.:format)                                                planes#show
#                               PATCH  /planes/:id(.:format)                                                planes#update
#                               PUT    /planes/:id(.:format)                                                planes#update
#                               DELETE /planes/:id(.:format)                                                planes#destroy
#                       flights GET    /flights(.:format)                                                   flights#index
#                               POST   /flights(.:format)                                                   flights#create
#                    new_flight GET    /flights/new(.:format)                                               flights#new
#                   edit_flight GET    /flights/:id/edit(.:format)                                          flights#edit
#                        flight GET    /flights/:id(.:format)                                               flights#show
#                               PATCH  /flights/:id(.:format)                                               flights#update
#                               PUT    /flights/:id(.:format)                                               flights#update
#                               DELETE /flights/:id(.:format)                                               flights#destroy
#                         users GET    /users(.:format)                                                     users#index
#                               POST   /users(.:format)                                                     users#create
#                      new_user GET    /users/new(.:format)                                                 users#new
#                     edit_user GET    /users/:id/edit(.:format)                                            users#edit
#                          user GET    /users/:id(.:format)                                                 users#show
#                               PATCH  /users/:id(.:format)                                                 users#update
#                               PUT    /users/:id(.:format)                                                 users#update
#                               DELETE /users/:id(.:format)                                                 users#destroy
#                          root GET    /                                                                    pages#app
#                        signup GET    /signup(.:format)                                                    pages#signup
#                         login GET    /login(.:format)                                                     pages#login
#                               POST   /login(.:format)                                                     session#create
#                               DELETE /login(.:format)                                                     session#destroy
#

Rails.application.routes.draw do

  resources :planes do
    resources :flights do
      resources :reservations
    end
  end

  resources :reservations
  resources :flights
  resources :users
  root :to => 'pages#app'

  get '/signup' => 'pages#signup'
  get '/login' => 'pages#login'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  password_digest :string
#  admin           :boolean
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string
#

class User < ActiveRecord::Base
  has_many :reservations
  has_many :flights, through: :reservations

  has_secure_password
  
  ##error handling for things like "no blank names"
  validates :name, :presence => true
  validates :name, :uniqueness => true #case-sensative
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @reservations = Reservation.where :user_id => @user.id
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :password, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<p>
  <strong>Reservations:</strong>
  <% i = 1 %>
  <% @reservations.each do |rsvp| %>
    <div><%= "Reservation #{i}: " %><% i += 1 %>
      <td><%= "Row: #{rsvp.row}" %></td>
      <td><%= "Col: #{rsvp.column}" %></td>
      <td><%= link_to 'Edit', edit_reservation_path(rsvp) %></td>
    </div>
  <% end %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'New Reservation', new_reservation_path %> |
<%= link_to 'Back', users_path %>